// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBTy0Rcu4PxgbMZe--pTCAymzAgAWBkk',
    appId: '1:618860934474:web:adab87bba3be459fdefdb3',
    messagingSenderId: '618860934474',
    projectId: 'expense-tracker-f7d15',
    authDomain: 'expense-tracker-f7d15.firebaseapp.com',
    storageBucket: 'expense-tracker-f7d15.firebasestorage.app',
    measurementId: 'G-ZMJRE6PJ0Y',
     static const String webClientId =
      '618860934474-so5bft1dek3cfguvhctmhlq08njd5lpf.apps.googleusercontent.com';
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqUI6gNTJgp0SUuiY0GC9OQBUKXAUXsI',
    appId: '1:618860934474:android:fbecd8c8d34e04f6defdb3',
    messagingSenderId: '618860934474',
    projectId: 'expense-tracker-f7d15',
    storageBucket: 'expense-tracker-f7d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenlGqZS4bGhevfrx9VJAD52lP1H-g3F8',
    appId: '1:618860934474:ios:65ff7a94c6a935aedefdb3',
    messagingSenderId: '618860934474',
    projectId: 'expense-tracker-f7d15',
    storageBucket: 'expense-tracker-f7d15.firebasestorage.app',
    iosClientId: '618860934474-n88q81a3gv32ssfjdp7c35cp6d7i7pn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
